CREATE DATABASE IF NOT EXISTS lojadb
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_general_ci;

USE lojadb;

CREATE TABLE IF NOT EXISTS clientes(
	id_cliente INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
	telefone VARCHAR(20) UNIQUE NOT NULL,
    sexo ENUM('M', 'F') NOT NULL,
    idade DATE NOT NULL
) DEFAULT CHARSET = utf8mb4;
